version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snyp

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80
    environment:
      - POSTGRES_DSN=host=db user=postgres password=postgres database=snyp sslmode=disable
    depends_on:
      - db
